# Use Python 3.9-slim-buster as the base image
FROM python:3.9-slim-buster

# Set the working directory to /app
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Copy the rest of the application code into the container
COPY . .

# Expose port 8000 for the FastAPI app to listen on
EXPOSE 8000

# Start the FastAPI app
CMD ["uvicorn", "Server:app", "--host", "0.0.0.0", "--port", "8000"]

#FROM python:3.9-slim-buster
#
## Set the working directory to /app
#WORKDIR /app
#
## Copy the requirements file into the container
#COPY requirements.txt .
#
## Install any needed packages specified in requirements.txt
#RUN pip install --trusted-host pypi.python.org -r requirements.txt
#
## Copy the rest of the application code into the container
#COPY .. .
#
## Expose port 80 for the FastAPI app to listen on
#EXPOSE 8000
#
## Start the FastAPI app
#CMD ["uvicorn", "Server:app", "--reload"]